spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reference
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/master.yml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: das
      password: das

  h2:
    console:
      path: /h2
      enabled: true
#      settings:
#        web-allow-others: true
#        trace: true
      settings.trace: false
      settings.web-allow-others: false


